const actionTypes = Object.freeze({
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    USER_LOGOUT: 'USER_LOGOUT',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    FETCH_USER_INFOR_SUCCESS: 'FETCH_USER_INFOR_SUCCESS',
    FETCH_USER_INFOR_FAIL: 'FETCH_USER_INFOR_FAIL',

    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED',

    EDIT_CART_SUCCESS: 'EDIT_CART_SUCCESS',
    EDIT_CART_FAILED: 'EDIT_CART_FAILED',

    DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
    DELETE_CART_FAILED: 'DELETE_CART_FAILED',

    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_FAILED: 'FETCH_CART_FAILED',

    //admin
    CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
    CREATE_ITEM_FAILED: 'CREATE_ITEM_FAILED',

    EDIT_ITEM_SUCCESS: 'EDIT_ITEM_SUCCESS',
    EDIT_ITEM_FAILED: 'EDIT_ITEM_FAILED',

    DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILED: 'DELETE_ITEM_FAILED',

    FETCH_ALL_ITEM_SUCCESS: 'FETCH_ALL_ITEM_SUCCESS',
    FETCH_ALL_ITEM_FAILED: 'FETCH_ALL_ITEM_FAILED',

    FETCH_IMPORTED_FRUIT_SUCCESS: 'FETCH_IMPORTED_FRUIT_SUCCESS',
    FETCH_IMPORTED_FRUIT_FAILED: 'FETCH_IMPORTED_FRUIT_FAILED',

    FETCH_FRUIT_BASKET_SUCCESS: 'FETCH_FRUIT_BASKET_SUCCESS',
    FETCH_FRUIT_BASKET_FAILED: 'FETCH_FRUIT_BASKET_FAILED',

    FETCH_FRUIT_BASKET_300_SUCCESS: 'FETCH_FRUIT_BASKET_300_SUCCESS',
    FETCH_FRUIT_BASKET_300_FAILED: 'FETCH_FRUIT_BASKET_300_FAILED',

    FETCH_FRUIT_BASKET_400_SUCCESS: 'FETCH_FRUIT_BASKET_400_SUCCESS',
    FETCH_FRUIT_BASKET_400_FAILED: 'FETCH_FRUIT_BASKET_400_FAILED',

    FETCH_FRUIT_BASKET_500_SUCCESS: 'FETCH_FRUIT_BASKET_500_SUCCESS',
    FETCH_FRUIT_BASKET_500_FAILED: 'FETCH_FRUIT_BASKET_500_FAILED',

    FETCH_FRUIT_BASKET_600_SUCCESS: 'FETCH_FRUIT_BASKET_600_SUCCESS',
    FETCH_FRUIT_BASKET_600_FAILED: 'FETCH_FRUIT_BASKET_600_FAILED',

    FETCH_FRUIT_BASKET_700_SUCCESS: 'FETCH_FRUIT_BASKET_700_SUCCESS',
    FETCH_FRUIT_BASKET_700_FAILED: 'FETCH_FRUIT_BASKET_700_FAILED',

    FETCH_CHERRY_SUCCESS: 'FETCH_CHERRY_SUCCESS',
    FETCH_CHERRY_FAILED: 'FETCH_CHERRY_FAILED',

    FETCH_BLUEBERRY_SUCCESS: 'FETCH_BLUEBERRY_SUCCESS',
    FETCH_BLUEBERRY_FAILED: 'FETCH_BLUEBERRY_FAILED',

    FETCH_APPLE_SUCCESS: 'FETCH_APPLE_SUCCESS',
    FETCH_APPLE_FAILED: 'FETCH_APPLE_FAILED',

    FETCH_GRAPE_SUCCESS: 'FETCH_GRAPE_SUCCESS',
    FETCH_GRAPE_FAILED: 'FETCH_GRAPE_FAILED',

    FETCH_KIWI_SUCCESS: 'FETCH_KIWI_SUCCESS',
    FETCH_KIWI_FAILED: 'FETCH_KIWI_FAILED',

    FETCH_ORANGE_SUCCESS: 'FETCH_ORANGE_SUCCESS',
    FETCH_ORANGE_FAILED: 'FETCH_ORANGE_FAILED',

    FETCH_TANGERINE_SUCCESS: 'FETCH_TANGERINE_SUCCESS',
    FETCH_TANGERINE_FAILED: 'FETCH_TANGERINE_FAILED',

    FETCH_DETAIL_ITEM_BY_ID_SUCCESS: 'FETCH_DETAIL_ITEM_BY_ID_SUCCESS',
    FETCH_DETAIL_ITEM_BY_ID_FAILED: 'FETCH_DETAIL_ITEM_BY_ID_FAILED',
})

export default actionTypes